# Generated by Django 2.0.2 on 2021-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=2, max_digits=4)),
                ('num_one', models.DecimalField(decimal_places=2, max_digits=4)),
                ('num_two', models.DecimalField(decimal_places=2, max_digits=4)),
                ('operator', models.CharField(max_length=1)),
            ],
        ),
    ]
