# Generated by Django 3.2.4 on 2021-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=2, max_digits=4)),
                ('num_one', models.DecimalField(decimal_places=2, max_digits=4)),
                ('num_two', models.DecimalField(decimal_places=2, max_digits=4)),
                ('operator', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Calculate',
        ),
    ]
