# Generated by Django 3.2.4 on 2021-06-23 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_auto_20210622_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='calc_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
